dist: xenial
language: go

go:
  - 1.12.7

env:
  global:
    - TAG="ci"
    - CODECOV_TOKEN="d1e39bea-f800-45de-8266-3e9b85e2594a"
  matrix:
    - XC_ARCH="amd64"
      BASEIMAGE="ubuntu:16.04"
    #- XC_ARCH="arm64"
    #  BASEIMAGE="arm64v8/ubuntu:18.04"

sudo: required

services:
  - docker

addons:
  apt:
    update: true
    packages: 
      - gcc-multilib

install:
  - make bootstrap
  - sudo apt-get install --yes libudev-dev
  - if [ "$TRAVIS_BUILD_DIR" != "$GOPATH/src/github.com/openebs/node-disk-manager" ]; then
      mkdir -p $GOPATH/src/github.com/openebs/;
      mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/openebs;
      cd $GOPATH/src/github.com/openebs/node-disk-manager;
    fi
  - if [ "$XC_ARCH" == "amd64" ]; then
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.0.0/minikube-linux-amd64;
      sudo chmod +x minikube;
      sudo mv minikube /usr/local/bin/;
    fi
  # we need openSeaChest repo to build node-disk-manager
  - pushd .
  - cd ..
  # Hotfix-Makefile_fix is the Release-19.06 with certain fixes in Makefile
  - git clone --recursive --branch Release-19.06.02 https://github.com/openebs/openSeaChest.git
  - cd openSeaChest/Make/gcc 
  - make release
  - cd ../../
  - sudo cp opensea-common/Make/gcc/lib/libopensea-common.a /usr/lib 
  - sudo cp opensea-operations/Make/gcc/lib/libopensea-operations.a /usr/lib 
  - sudo cp opensea-transport/Make/gcc/lib/libopensea-transport.a /usr/lib
  - popd 

before_script:
  - if [ "$XC_ARCH" == "amd64" ]; then
      sudo minikube start --vm-driver=none --cpus=1 --memory=1024;
      sudo minikube update-context;
      sudo chown -R $USER $HOME/.minikube;
      sudo chown -R $USER $HOME/.kube;
      make shellcheck;
    fi

script:
  - make
  # Here sudo -E env "PATH=$PATH" make test is required for running tests with
  # sudo permissions since we are making use of scsi device mockdata in smartprobe_test
  # which could be fetched for a SCSI device with sudo permissions only since to access
  # a particular scsi device, sudo or root permissions are required.
  - if [ "$XC_ARCH" == "amd64" ]; then
      sudo -E env "PATH=$PATH" make test;
      make integration-test;
      bash <(curl -s https://codecov.io/bash);
    fi

after_success:
  - DIMAGE=openebs/node-disk-manager-$XC_ARCH ./build/push;
  - DIMAGE=openebs/node-disk-operator-$XC_ARCH ./build/push;
