name: build

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: |
          BRANCH="${GITHUB_REF##*/}"
          CI_TAG=${BRANCH}-ci
          if [ ${BRANCH} = "master" ]; then
            CI_TAG="ci"
          fi
          echo "::set-env name=TAG::${CI_TAG}"
          echo "::set-env name=BRANCH::{BRANCH}"
          echo "BRANCH: ${BRANCH}"
          echo "TAG: ${CI_TAG}"
