name: release

on:
  create:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  ndm-daemonset:
    runs-on: ubuntu-latest
    env:
      TAG: $(git describe --abbrev=0)
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        env:
          IMAGE_ORG: akhilerm
        run: |
          make docker.buildx.ndm

  ndm-exporter:
    runs-on: ubuntu-latest
    env:
      TAG: $(git describe --abbrev=0)
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        env:
          IMAGE_ORG: akhilerm
        run: |
          make docker.buildx.exporter

  ndm-operator:
    runs-on: ubuntu-latest
    env:
      TAG: $(git describe --abbrev=0)
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        env:
          IMAGE_ORG: akhilerm
        run: |
          make docker.buildx.ndo
