name: release

on:
  create:
    tags:
      - 'v*'

jobs:
  ndm-daemonset:
    runs-on: ubuntu-latest
    env:
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Tag
        run: |
          "echo ::set-env name=TAG::${GITHUB_REF#refs/*/v}"
          "echo ::set-env name=RELEASE_TAG::${TAG}"

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build & Push Image
        run: |
          make docker.buildx.ndm
          make buildx.push.ndm

  ndm-exporter:
    runs-on: ubuntu-latest
    env:
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Tag
        run: |
          "echo ::set-env name=TAG::${GITHUB_REF#refs/*/v}"
          "echo ::set-env name=RELEASE_TAG::${TAG}"


      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        run: |
          make docker.buildx.exporter
          make buildx.push.exporter

  ndm-operator:
    runs-on: ubuntu-latest
    env:
      IMAGE_ORG: 'akhilerm'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Tag
        run: |
          "echo ::set-env name=TAG::${GITHUB_REF#refs/*/v}"
          "echo ::set-env name=RELEASE_TAG::${TAG}"


      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Image
        run: |
          make docker.buildx.ndo
          make buildx.push.ndo
