name: release

on:
  create:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: set tag
        run: "echo ::set-env name=TAG::${GITHUB_REF#refs/*/v}"

      - name: get tag
        run: echo "Tag:"$TAG " end tag"