name: test

on: ['push', 'pull_request']

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install-dep

      - name: Verify Unit Tests
        run: sudo -E env "PATH=$PATH" make test